version: '2'
services:
  proyectos-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/proyectos/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=proyectos
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
